import { motion } from 'framer-motion';
import { ArrowRight, CheckCircle2, Rocket, Sparkles } from 'lucide-react';
import { BlogCard, CaseStudyCard, PricingCard, ServiceCard, StatCard, TestimonialCard } from '../components/Cards.jsx';
import FAQItem from '../components/FAQItem.jsx';
import LeadForm from '../components/LeadForm.jsx';
import { GradientButton, Reveal, SectionTitle } from '../components/ui.jsx';
import { blogs } from '../data/blogs.js';
import { caseStudies } from '../data/caseStudies.js';
import { faqs } from '../data/faq.js';
import { pricing } from '../data/pricing.js';
import { services } from '../data/services.js';
import { brands, industries, platforms, stats } from '../data/siteData.js';
import { testimonials } from '../data/testimonials.js';

export default function Home(){return <><Hero/><Trust/><Stats/><Services/><Why/><Process/><Cases/><Industries/><Platforms/><About/><Testimonials/><Pricing/><Audit/><FAQ/><Blog/><FinalCTA/></>}
function Hero(){const cards=[['Revenue Growth','+148%'],['Leads Generated','2,850'],['ROAS','6.4x'],['Conversion Rate','8.7%']];return <section className="mesh min-h-screen pt-32"><div className="container grid items-center gap-12 pb-20 lg:grid-cols-2"><Reveal><span className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-sm font-extrabold shadow"><Rocket size={16}/> Growth-Focused Go Digital 24x7</span><h1 className="mt-6 text-5xl font-extrabold leading-tight md:text-7xl">Turn Clicks Into <span className="gradient-text">Customers</span> & <span className="gradient-text">Grow Faster</span>.</h1><p className="mt-6 text-lg text-slate-600 md:text-xl">We combine strategy, creativity, data and technology to build campaigns that generate real leads, sales and measurable growth.</p><div className="mt-8 flex flex-wrap gap-4"><GradientButton>Get Free Marketing Audit</GradientButton><GradientButton to="/portfolio" ghost>View Our Work <ArrowRight size={18}/></GradientButton></div><div className="mt-8 flex flex-wrap gap-5 text-sm font-bold text-slate-600"><span>4.9/5 Client Rating*</span><span>100+ Projects Delivered*</span><span>5+ Years Experience*</span></div><p className="mt-2 text-xs text-slate-400">*Editable demo placeholders.</p></Reveal><div className="relative"><motion.div animate={{y:[0,-12,0]}} transition={{repeat:Infinity,duration:5}} className="glass rounded-[2rem] p-6"><div className="mb-5 flex items-center justify-between"><b>Growth Dashboard</b><Sparkles className="text-[#FF3CAC]"/></div><div className="grid gap-4 sm:grid-cols-2">{cards.map(([a,b],i)=><motion.div key={a} initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:i*.12}} className="rounded-3xl bg-white p-5 shadow-lg"><p className="text-sm text-slate-500">{a}</p><p className="mt-2 text-3xl font-extrabold gradient-text">{b}</p></motion.div>)}</div><div className="mt-6 flex h-48 items-end gap-3 rounded-3xl bg-[#0B1020] p-5">{[45,72,58,92,68,112,138].map((h,i)=><div key={i} className="flex-1 rounded-t-xl bg-gradient-to-t from-[#6C3BFF] to-[#00D4FF]" style={{height:h}}/> )}</div></motion.div></div></div></section>}
function Trust(){return <section className="bg-white py-10"><div className="container"><p className="text-center font-extrabold text-slate-500">Trusted by ambitious brands</p><div className="mt-7 flex flex-wrap justify-center gap-4">{brands.map(b=><span className="rounded-full border px-6 py-3 font-extrabold text-slate-400 transition hover:border-[#6C3BFF] hover:text-[#6C3BFF]" key={b}>{b}</span>)}</div></div></section>}
function Stats(){return <section className="section"><div className="container grid gap-5 md:grid-cols-4">{stats.map(s=><StatCard key={s.label} item={s}/>)}</div></section>}
function Services(){return <section className="section bg-white" id="services"><div className="container"><SectionTitle eyebrow="Services" title="Everything You Need To Grow Online" subtitle="From brand awareness to qualified leads and sales, we create digital strategies designed to move your business forward."/><div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{services.map(s=><ServiceCard key={s.slug} s={s}/>)}</div></div></section>}
function Why(){const reasons=['Data-Driven Strategies','Performance-Focused Campaigns','Transparent Reporting','Creative + Technology Expertise','Dedicated Growth Strategy','Conversion-Focused Approach'];return <section className="section mesh"><div className="container grid items-center gap-10 lg:grid-cols-2"><Reveal><div className="glass rounded-[2rem] p-8"><div className="grid grid-cols-3 gap-3">{[80,52,105,70,130,95].map((h,i)=><div className="rounded-2xl bg-gradient-to-t from-[#FF3CAC] to-[#6C3BFF]" style={{height:h}} key={i}/>)}</div></div></Reveal><Reveal><h2 className="text-4xl font-extrabold md:text-5xl">We Don't Chase Vanity Metrics. We Focus On Business Growth.</h2><div className="mt-7 grid gap-4">{reasons.map(r=><p className="flex gap-3 font-bold" key={r}><CheckCircle2 className="text-[#00C896]"/> {r}</p>)}</div></Reveal></div></section>}
function Process(){const steps=['Discover','Strategy','Create','Launch','Optimize','Scale'];return <section className="section dark"><div className="container"><SectionTitle dark eyebrow="Process" title="How We Turn Ideas Into Growth"/><div className="grid gap-5 md:grid-cols-3 lg:grid-cols-6">{steps.map((s,i)=><Reveal key={s}><div className="rounded-3xl bg-white/10 p-5"><b className="gradient-text text-3xl">0{i+1}</b><h3 className="mt-3 text-xl font-extrabold">{s}</h3><p className="mt-3 text-sm text-white/65">{['Understand the business, customers and competition.','Build a customized marketing roadmap.','Create campaigns, content and digital experiences.','Launch campaigns across relevant channels.','Continuously improve performance.','Scale what produces sustainable results.'][i]}</p></div></Reveal>)}</div></div></section>}
function Cases(){return <section className="section"><div className="container"><SectionTitle eyebrow="Case Studies" title="Real Strategies. Real Growth." subtitle="Demo result cards with editable placeholder outcomes."/><div className="grid gap-7 lg:grid-cols-3">{caseStudies.map(c=><CaseStudyCard key={c.title} c={c}/>)}</div></div></section>}
function Industries(){return <section className="section bg-white"><div className="container"><SectionTitle eyebrow="Industries" title="Industries We Help"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{industries.map(([name,Icon])=><Reveal key={name}><div className="flex items-center gap-4 rounded-3xl border bg-white p-5 shadow-sm"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#F8F9FF] text-[#6C3BFF]"><Icon/></span><b>{name}</b></div></Reveal>)}</div></div></section>}
function Platforms(){return <section className="overflow-hidden py-12"><div className="container"><SectionTitle eyebrow="Platforms" title="Powered By The Platforms Your Customers Use"/></div><div className="marquee flex w-[200%] gap-4">{[...platforms,...platforms].map((p,i)=><span className="rounded-full bg-white px-7 py-4 font-extrabold shadow" key={p+i}>{p}</span>)}</div></section>}
function About(){return <section className="section mesh"><div className="container grid gap-10 lg:grid-cols-2"><Reveal><h2 className="text-4xl font-extrabold md:text-5xl">Creative Minds. Data-Driven Decisions.</h2><p className="mt-5 text-lg text-slate-600">We're a growth-focused digital marketing team combining creativity, technology and performance marketing to help businesses build stronger brands and generate measurable results.</p><div className="mt-7 grid grid-cols-2 gap-4">{['5+ Years Experience*','100+ Projects*','50+ Happy Clients*','10+ Industries*'].map(x=><div className="rounded-3xl bg-white p-5 font-extrabold shadow" key={x}>{x}</div>)}</div></Reveal><Reveal><div className="grid grid-cols-2 gap-4"><img className="h-56 rounded-3xl object-cover" src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=600&q=80" alt="Agency team workshop"/><img className="mt-10 h-56 rounded-3xl object-cover" src="https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=600&q=80" alt="Marketing strategy meeting"/></div></Reveal></div></section>}
function Testimonials(){return <section className="section bg-white"><div className="container"><SectionTitle eyebrow="Testimonials" title="What Clients Say" subtitle="Demo testimonials for layout preview."/><div className="flex gap-5 overflow-x-auto pb-4">{testimonials.map(t=><TestimonialCard key={t.name} t={t}/>)}</div></div></section>}
function Pricing(){return <section className="section"><div className="container"><SectionTitle eyebrow="Pricing" title="Flexible Packages For Every Growth Stage"/><div className="grid gap-7 lg:grid-cols-3">{pricing.map(p=><PricingCard key={p.name} p={p}/>)}</div></div></section>}
function Audit(){return <section id="audit" className="section bg-gradient-to-br from-[#6C3BFF] via-[#2F80ED] to-[#00D4FF]"><div className="container grid gap-10 lg:grid-cols-2"><Reveal><h2 className="text-4xl font-extrabold text-white md:text-5xl">Not Sure What's Holding Your Marketing Back?</h2><p className="mt-5 text-lg text-white/80">Get a free digital marketing audit and discover opportunities to improve your traffic, leads and conversions.</p></Reveal><LeadForm/></div></section>}
function FAQ(){return <section className="section"><div className="container"><SectionTitle eyebrow="FAQ" title="Questions Before We Start?"/><div className="mx-auto grid max-w-3xl gap-4">{faqs.map(([q,a])=><FAQItem key={q} q={q} a={a}/>)}</div></div></section>}
function Blog(){return <section className="section bg-white"><div className="container"><SectionTitle eyebrow="Blog" title="Fresh Marketing Thinking"/><div className="grid gap-7 lg:grid-cols-3">{blogs.map(b=><BlogCard key={b.title} b={b}/>)}</div></div></section>}
function FinalCTA(){return <section className="section bg-gradient-to-r from-[#FF8A00] via-[#FF3CAC] to-[#6C3BFF] text-white"><div className="container text-center"><h2 className="text-4xl font-extrabold md:text-6xl">Ready To Turn Your Marketing Into A Growth Engine?</h2><p className="mx-auto mt-5 max-w-2xl text-lg text-white/85">Let's create a digital strategy designed around your business goals.</p><div className="mt-8 flex justify-center gap-4"><GradientButton to="/contact">Book Free Strategy Call</GradientButton><GradientButton to="/contact" ghost>Contact Us</GradientButton></div></div></section>}


