import { ArrowLeft, CheckCircle2 } from 'lucide-react';
import { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import LeadForm from '../components/LeadForm.jsx';
import { ServiceCard } from '../components/Cards.jsx';
import { services } from '../data/services.js';
export default function ServiceDetail(){const{slug}=useParams();const service=services.find(s=>s.slug===slug);useEffect(()=>{document.title=`${service?.title||'Service'} | Go Digital 24x7`},[service]);if(!service)return <section className="section pt-36"><div className="container"><h1 className="text-4xl font-extrabold">Service not found</h1><Link to="/services">Back to services</Link></div></section>;const Icon=service.icon;return <><section className="mesh pt-36 pb-20"><div className="container grid items-center gap-10 lg:grid-cols-2"><div><Link className="mb-6 inline-flex gap-2 font-bold text-[#6C3BFF]" to="/services"><ArrowLeft/> All services</Link><h1 className="text-5xl font-extrabold md:text-7xl">{service.title}</h1><p className="mt-5 text-xl text-slate-600">{service.desc} Built with creative testing, clear reporting and conversion-first strategy.</p><a className="btn btn-primary mt-8" href="#audit">Get a free audit</a></div><div className={`grid min-h-80 place-items-center rounded-[2rem] bg-gradient-to-br ${service.gradient} text-white shadow-2xl`}><Icon size={110}/></div></div></section><section className="section bg-white"><div className="container grid gap-8 lg:grid-cols-3"><div className="lg:col-span-2"><h2 className="text-4xl font-extrabold">What this service includes</h2><div className="mt-8 grid gap-4 md:grid-cols-2">{['Strategy roadmap','Creative direction','Campaign setup','Landing page review','Weekly optimization','Monthly reporting'].map(x=><p className="flex gap-3 rounded-2xl bg-[#F8F9FF] p-4 font-bold" key={x}><CheckCircle2 className="text-[#00C896]"/> {x}</p>)}</div></div><div className="rounded-3xl bg-[#0B1020] p-7 text-white"><h3 className="text-2xl font-extrabold">Best for</h3><p className="mt-4 text-white/70">Brands that want clearer acquisition channels, better conversion rates and a practical growth plan.</p></div></div></section><section id="audit" className="section"><div className="container"><LeadForm/></div></section></>}


