import { ArrowRight, Check, Star } from 'lucide-react';
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { AnimatedCounter, Reveal } from './ui.jsx';
export function ServiceCard({s}){const Icon=s.icon;return <Reveal><Link to={`/services/${s.slug}`} className="group block h-full rounded-3xl bg-white p-[1px] shadow-xl shadow-slate-200/70"><div className="h-full rounded-3xl bg-white p-7 transition group-hover:-translate-y-1"><div className={`mb-6 grid h-14 w-14 place-items-center rounded-2xl bg-gradient-to-br ${s.gradient} text-white shadow-lg`}><Icon/></div><h3 className="text-xl font-extrabold">{s.title}</h3><p className="mt-3 text-slate-600">{s.desc}</p><span className="mt-6 flex items-center gap-2 font-extrabold text-[#6C3BFF]">Learn More <ArrowRight size={18}/></span></div></Link></Reveal>}
export function StatCard({item}){return <Reveal><motion.div whileHover={{y:-8}} className={`rounded-3xl bg-gradient-to-br ${item.color} p-6 text-white shadow-2xl`}><p className="text-4xl font-extrabold"><AnimatedCounter value={item.value} suffix={item.suffix}/></p><p className="mt-2 font-semibold text-white/85">{item.label}</p></motion.div></Reveal>}
export function CaseStudyCard({c}){return <Reveal><motion.article whileHover={{y:-8}} className="group overflow-hidden rounded-3xl bg-[#0B1020] text-white shadow-2xl"><div className="relative h-64 overflow-hidden"><img className="h-full w-full object-cover transition duration-500 group-hover:scale-110" src={c.image} alt={c.title}/><div className="absolute inset-0 bg-gradient-to-t from-[#0B1020] to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-white/20 px-4 py-2 text-sm font-bold backdrop-blur">{c.category}</span></div><div className="p-6"><h3 className="text-2xl font-extrabold">{c.title}</h3><div className="mt-5 grid gap-3">{c.results.map(r=><span key={r} className="rounded-2xl bg-white/10 px-4 py-3 font-bold">{r}</span>)}</div><button className="btn btn-primary mt-6">View Case Study</button></div></motion.article></Reveal>}
export function PricingCard({p}){return <Reveal><div className={`relative rounded-3xl p-7 shadow-2xl ${p.hot?'bg-[#0B1020] text-white':'bg-white'}`}>{p.hot&&<span className="absolute -top-4 left-7 rounded-full bg-gradient-to-r from-[#FF8A00] to-[#FF3CAC] px-4 py-2 text-xs font-extrabold uppercase">Most Popular</span>}<p className="font-bold text-[#6C3BFF]">{p.tag}</p><h3 className="mt-3 text-3xl font-extrabold">{p.name}</h3><p className="mt-5 text-2xl font-extrabold">{p.price}</p><div className="mt-7 grid gap-3">{p.features.map(f=><p key={f} className="flex gap-3"><Check className="text-[#00C896]"/> {f}</p>)}</div><button className="btn btn-primary mt-8 w-full justify-center">Let's Talk</button></div></Reveal>}
export function TestimonialCard({t}){return <div className="min-w-[320px] rounded-3xl bg-white p-6 shadow-xl"><div className="flex gap-1 text-[#FFD600]">{Array.from({length:5}).map((_,i)=><Star key={i} fill="currentColor" size={18}/>)}</div><p className="mt-5 text-slate-700">"{t.quote}"</p><div className="mt-6 flex items-center gap-3"><img className="h-12 w-12 rounded-full object-cover" src={t.image} alt={t.name}/><div><b>{t.name}</b><p className="text-sm text-slate-500">{t.company} - {t.service}</p></div></div></div>}
export function BlogCard({b}){return <Reveal><article className="overflow-hidden rounded-3xl bg-white shadow-xl"><img className="h-56 w-full object-cover" src={b.image} alt={b.title}/><div className="p-6"><p className="text-sm font-extrabold text-[#6C3BFF]">{b.category} - {b.date}</p><h3 className="mt-3 text-xl font-extrabold">{b.title}</h3><p className="mt-3 text-slate-600">{b.desc}</p><a className="mt-5 inline-flex font-extrabold text-[#6C3BFF]">Read more</a></div></article></Reveal>}


